### ISSUE TITLE
No events calling back, auth seemingly not occuring.

### ISSUE THREAD

**Issue by EricApostal** [V3ntus/nyxx-self#12]
**Describe the bug**

**To Reproduce**
1. Paste `example.dart` file into `main.dart` of barebones Flutter template
2. Run the program
3. Observe nothing happening

**Expected behavior**

**Additional context**
I'm assuming this might be due to API changes in Discord, and this fork being out of sync. I'm reporting it in case I am the only person who can replicate this, or at least track it if it is indeed a package-wide bug.

**Comment by V3ntus** [comment]
Hey Eric, I'll try and see if I can reproduce this and get back with you. Anything in the debug logs worth noting?

**Comment by V3ntus** [comment]
@EricApostal I've merged upstream with this library and have gotten auth working again on the `dev` branch. Note I'm running the `example/example.dart` program here.
![image](https://github.com/V3ntus/nyxx-self/assets/29584664/2d16d101-085b-4496-82d8-162f965a7421)

**Comment by EricApostal** [comment]
@V3ntus Sorry for the delayed response, yes it works great now! I like how you handle application deferring.
